import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/app/components/footer";
import Header from "@/app/components/header";
import { inter } from "@/app/ui/fonts";
import StoreProvider from "./store-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter.className} antialiased flex flex-col min-h-screen`}
      >
        <StoreProvider>
          <Header />
          <main className="flex-grow">{children}</main>
          <Footer />
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
